name: Metaphorheaven
favicon: null
layout_spectrum: 0.5101183315273374
typography_spectrum: 0.6380557008087635
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.16163631761446595
  lightness: 0.4801595078315586
  saturation: 0.7952349602710456
  rhythmicContrast: 0.3177723493427038
purpose: []
